import Image from "next/image";
const Arrow=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg>;
export default function Home(){
 const gmail="https://mail.google.com/mail/?view=cm&fs=1&to=Deliriocafemadrid%40gmail.com&su=Consulta%20para%20Delirio%20Caf%C3%A9&body=Hola%2C%20os%20escribo%20para%20consultar%20sobre%20";
 return <main>
  <header><a className="logo" href="#inicio">DELIRIO<span>CAFÉ MADRID</span></a><nav><a href="#carta">La mesa</a><a href="#cafe">El café</a><a href="#visita">Ven</a></nav><a className="pill" href={gmail} target="_blank" rel="noreferrer">Escríbenos <Arrow/></a></header>
  <section className="hero" id="inicio"><div className="heroText"><p className="kicker">CAFÉ DE ESPECIALIDAD · LAVAPIÉS</p><h1>Un café<br/>y que pase<br/><em>lo que tenga</em><br/>que pasar.</h1><div className="intro"><p>Buen café, bollería artesanal y una mesa que no pregunta cuánto te vas a quedar.</p><a className="button" href="https://www.google.com/maps/search/?api=1&query=Delirio+Café+Madrid+Tribulete+21" target="_blank" rel="noreferrer">Cómo llegar <Arrow/></a></div></div><figure><Image src="/images/roll-coffee.jpg" alt="Roll de canela con pistacho y café" fill priority sizes="(max-width:800px) 100vw,50vw"/><figcaption>TRIBULETE 21 · TODOS LOS DÍAS</figcaption></figure></section>
  <div className="marquee"><span>ESPRESSO · FLAT WHITE · ROLLS · TOSTADAS · BOLLERÍA · </span><span>ESPRESSO · FLAT WHITE · ROLLS · TOSTADAS · BOLLERÍA · </span></div>
  <section className="statement" id="cafe"><p className="num">01 / EL CAFÉ</p><h2>Primero,<br/><span>que esté bueno.</span><br/>Luego ya hablamos.</h2><p className="side">Café de especialidad preparado con atención, sin convertir cada taza en una conferencia.</p></section>
  <section className="table"><div className="photo"><Image src="/images/shared-table.jpg" alt="Una mesa compartida con café, tostada y bollería" fill sizes="(max-width:800px) 100vw,58vw"/></div><div className="tableCopy"><p className="num">02 / LA MESA</p><h2>Ven a desayunar.<br/>Quédate por<br/><i>el momento.</i></h2><p>Aquí caben el café rápido, la charla larga, algo dulce y ese segundo pedido que no tenías pensado.</p><div className="mini"><span>CAFÉ</span><span>DULCE</span><span>SALADO</span></div></div></section>
  <section className="menu" id="carta"><div className="menuTitle"><p className="num">03 / PARA ELEGIR</p><h2>Lo difícil<br/>es pedir solo<br/><span>una cosa.</span></h2></div><div className="cards"><article><b>01</b><h3>Del horno</h3><p>Rolls, bollería y pastelería artesanal para acompañar el café o darle todo el protagonismo.</p></article><article><b>02</b><h3>De la máquina</h3><p>Espresso, café con leche y preparaciones hechas con buen grano y mejor mano.</p></article><article><b>03</b><h3>Para desayunar</h3><p>Tostadas y bocados salados para cuando lo dulce no basta —o llega después.</p></article></div></section>
  <section className="color"><p>NO ES UNA REUNIÓN.</p><h2>Es ese café<br/>que acaba<br/><span>alargando el día.</span></h2><a className="button light" href={gmail} target="_blank" rel="noreferrer">Tengo una consulta <Arrow/></a></section>
  <section className="visit" id="visita"><div><p className="num">04 / LAVAPIÉS</p><h2>Nos vemos<br/>en Tribulete.</h2></div><div className="info"><h3>Tribulete, 21<br/>Madrid</h3><p>Abierto todos los días<br/>09:30–19:30</p><a href="https://www.google.com/maps/search/?api=1&query=Delirio+Café+Madrid+Tribulete+21" target="_blank" rel="noreferrer">Abrir en Google Maps <Arrow/></a><a href={gmail} target="_blank" rel="noreferrer">Deliriocafemadrid@gmail.com <Arrow/></a></div></section>
  <footer><a className="logo" href="#inicio">DELIRIO<span>CAFÉ MADRID</span></a><p>Café de especialidad y pastelería artesanal en Lavapiés.</p><small>Propuesta visual · Imágenes y datos definitivos a confirmar con el negocio.</small></footer>
 </main>}
